// src/pages/Onboarding/constants.ts

export const salaryOptions = [
  { label: ">5,000$", value: "5000" },
  { label: ">10,000$", value: "10000" },
  { label: ">25,000$", value: "25000" },
  { label: ">50,000$", value: "50000" },
  { label: ">100,000$", value: "100000" },
  { label: ">150,000$", value: "150000" },
];

export const jobRoleOptions = [
  { value: '.Net', label: '.Net' },
  { value: 'Actimize Developer', label: 'Actimize Developer' },
  { value: 'Active Directory', label: 'Active Directory' },
  { value: 'Agronomy Operations', label: 'Agronomy Operations' },
  { value: 'Anti Money Laundering (AML)', label: 'Anti Money Laundering (AML)' },
  { value: 'Big Data Engineer', label: 'Big Data Engineer' },
  { value: 'Biotechnology', label: 'Biotechnology' },
  { value: 'Biotechnology Internship', label: 'Biotechnology Internship' },
  { value: 'Business Analyst', label: 'Business Analyst' },
  { value: 'Business Intelligence Engineer', label: 'Business Intelligence Engineer' },
  { value: 'CLINICAL DATA ANALYST', label: 'CLINICAL DATA ANALYST' },
  { value: 'Cloud Engineer', label: 'Cloud Engineer' },
  { value: 'Clinical Research Coordinator', label: 'Clinical Research Coordinator' },
  { value: 'Computer Science', label: 'Computer Science' },
  { value: 'Computer Science Internship', label: 'Computer Science Internship' },
  { value: 'Construction Management', label: 'Construction Management' },
  { value: 'CRM Sales', label: 'CRM Sales' },
  { value: 'CRM Specialist', label: 'CRM Specialist' },
  { value: 'Cyber security', label: 'Cyber security' },
  { value: 'Data Analyst', label: 'Data Analyst' },
  { value: 'Data Analyst Internships', label: 'Data Analyst Internships' },
  { value: 'Data Center Technician', label: 'Data Center Technician' },
  { value: 'Data Engineer', label: 'Data Engineer' },
  { value: 'Data Engineer (citizen/h4ead)', label: 'Data Engineer (citizen/h4ead)' },
  { value: 'Data science early grad', label: 'Data science early grad' },
  { value: 'Data Scientist', label: 'Data Scientist' },
  { value: 'Database Administration', label: 'Database Administration' },
  { value: 'DevOps', label: 'DevOps' },
  { value: 'DevOps Internships', label: 'DevOps Internships' },
  { value: 'Electrical Engineer', label: 'Electrical Engineer' },
  { value: 'Electrical Project', label: 'Electrical Project' },
  { value: 'Electronic Health Records (EHR)', label: 'Electronic Health Records (EHR)' },
  { value: 'Embedded software', label: 'Embedded software' },
  { value: 'Embedded Software Engineer', label: 'Embedded Software Engineer' },
  { value: 'Environmental Health and Safety (EHS)', label: 'Environmental Health and Safety (EHS)' },
].filter(role => !role.value.includes(',') && !role.value.toLowerCase().includes('for'));

export const locationOptions = [
  { value: "Remote", label: "Remote" },
  { value: "On-site", label: "On-site" },
  { value: "Hybrid", label: "Hybrid" },
];

export const US_STATES = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
  "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
  "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
  "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
  "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
].map(s => ({ value: s, label: s }));

export const COUNTRIES = [
  "United States", "Canada", "United Kingdom", "India", "Australia", "Germany", "France", "China", "Japan", "Brazil",
  "Mexico", "Italy", "Spain", "Russia", "South Korea", "Netherlands", "Turkey", "Switzerland", "Saudi Arabia", "Sweden",
  "Poland", "Belgium", "Austria", "Norway", "United Arab Emirates", "Ireland", "Denmark", "Singapore", "Malaysia", "South Africa"
].map(c => ({ value: c, label: c }));

export const addressSuggestions = [
  "123 5th Avenue, New York, NY, United States",
  "456 Broadway, New York, NY, United States",
  "789 Park Avenue, New York, NY, United States",
  "321 Madison Avenue, New York, NY, United States",
  "555 Lexington Avenue, New York, NY, United States",
  "100 Wall Street, New York, NY, United States",
  "200 Central Park West, New York, NY, United States",
  "1234 Hollywood Boulevard, Los Angeles, CA, United States",
  "5678 Sunset Boulevard, Los Angeles, CA, United States",
  "910 Wilshire Boulevard, Los Angeles, CA, United States",
  "345 Rodeo Drive, Beverly Hills, CA, United States",
  "678 Venice Boulevard, Los Angeles, CA, United States",
  "234 Santa Monica Boulevard, Los Angeles, CA, United States",
  "500 N Michigan Avenue, Chicago, IL, United States",
  "123 S State Street, Chicago, IL, United States",
  "789 W Lake Street, Chicago, IL, United States",
  "456 N Clark Street, Chicago, IL, United States",
  "234 E Wacker Drive, Chicago, IL, United States",
  "1000 Main Street, Houston, TX, United States",
  "2500 Westheimer Road, Houston, TX, United States",
  "3456 Richmond Avenue, Houston, TX, United States",
  "789 E Camelback Road, Phoenix, AZ, United States",
  "456 N Central Avenue, Phoenix, AZ, United States",
  "123 Market Street, Philadelphia, PA, United States",
  "456 Walnut Street, Philadelphia, PA, United States",
  "789 Chestnut Street, Philadelphia, PA, United States",
  "500 Commerce Street, San Antonio, TX, United States",
  "1234 N St Mary's Street, San Antonio, TX, United States",
  "678 Broadway, San Diego, CA, United States",
  "123 Harbor Drive, San Diego, CA, United States",
  "1500 Elm Street, Dallas, TX, United States",
  "2000 McKinney Avenue, Dallas, TX, United States",
  "123 Santa Clara Street, San Jose, CA, United States",
  "456 1st Street, San Jose, CA, United States",
  "789 Congress Avenue, Austin, TX, United States",
  "234 6th Street, Austin, TX, United States",
  "100 Beach Boulevard, Jacksonville, FL, United States",
  "500 Bay Street, Jacksonville, FL, United States",
  "123 Main Street, Fort Worth, TX, United States",
  "456 Houston Street, Fort Worth, TX, United States",
  "789 High Street, Columbus, OH, United States",
  "234 Broad Street, Columbus, OH, United States",
  "123 Tryon Street, Charlotte, NC, United States",
  "456 College Street, Charlotte, NC, United States",
  "100 Market Street, San Francisco, CA, United States",
  "500 Montgomery Street, San Francisco, CA, United States",
  "789 Mission Street, San Francisco, CA, United States",
  "123 Meridian Street, Indianapolis, IN, United States",
  "456 Massachusetts Avenue, Indianapolis, IN, United States",
  "100 Pine Street, Seattle, WA, United States",
  "500 1st Avenue, Seattle, WA, United States",
  "123 16th Street, Denver, CO, United States",
  "456 Colfax Avenue, Denver, CO, United States",
  "100 Boylston Street, Boston, MA, United States",
  "200 Newbury Street, Boston, MA, United States",
  "500 Commonwealth Avenue, Boston, MA, United States",
  "123 Broadway, Nashville, TN, United States",
  "456 Music Row, Nashville, TN, United States",
  "100 Woodward Avenue, Detroit, MI, United States",
  "500 Jefferson Avenue, Detroit, MI, United States",
  "123 SW Morrison Street, Portland, OR, United States",
  "456 NW 23rd Avenue, Portland, OR, United States",
  "100 Las Vegas Boulevard, Las Vegas, NV, United States",
  "500 Fremont Street, Las Vegas, NV, United States",
  "100 Biscayne Boulevard, Miami, FL, United States",
  "500 Ocean Drive, Miami Beach, FL, United States",
  "123 Peachtree Street, Atlanta, GA, United States",
  "456 Marietta Street, Atlanta, GA, United States",
  "100 Fayetteville Street, Raleigh, NC, United States",
  "234 Hillsborough Street, Raleigh, NC, United States",
  "100 Hennepin Avenue, Minneapolis, MN, United States",
  "234 Nicollet Avenue, Minneapolis, MN, United States",
  "123 Franklin Street, Tampa, FL, United States",
  "456 Kennedy Boulevard, Tampa, FL, United States",
  "100 Orange Avenue, Orlando, FL, United States",
  "234 Church Street, Orlando, FL, United States",
  "10 Downing Street, London, England, United Kingdom",
  "221B Baker Street, London, England, United Kingdom",
  "123 Oxford Street, London, England, United Kingdom",
  "456 Regent Street, London, England, United Kingdom",
  "789 Piccadilly, London, England, United Kingdom",
  "100 The Strand, London, England, United Kingdom",
  "50 Kensington High Street, London, England, United Kingdom",
  "25 Bond Street, London, England, United Kingdom",
  "123 Deansgate, Manchester, England, United Kingdom",
  "456 Market Street, Manchester, England, United Kingdom",
  "789 King Street, Manchester, England, United Kingdom",
  "100 New Street, Birmingham, England, United Kingdom",
  "234 Corporation Street, Birmingham, England, United Kingdom",
  "456 Broad Street, Birmingham, England, United Kingdom",
  "123 Briggate, Leeds, England, United Kingdom",
  "456 The Headrow, Leeds, England, United Kingdom",
  "100 Buchanan Street, Glasgow, Scotland, United Kingdom",
  "234 Sauchiehall Street, Glasgow, Scotland, United Kingdom",
  "123 Princes Street, Edinburgh, Scotland, United Kingdom",
  "456 Royal Mile, Edinburgh, Scotland, United Kingdom",
  "789 George Street, Edinburgh, Scotland, United Kingdom",
  "100 Bold Street, Liverpool, England, United Kingdom",
  "234 Church Street, Liverpool, England, United Kingdom",
  "123 Park Street, Bristol, England, United Kingdom",
  "456 Baldwin Street, Bristol, England, United Kingdom",
  "100 Fargate, Sheffield, England, United Kingdom",
  "234 High Street, Sheffield, England, United Kingdom",
  "123 Queen Street, Cardiff, Wales, United Kingdom",
  "456 St Mary Street, Cardiff, Wales, United Kingdom",
  "100 Royal Avenue, Belfast, Northern Ireland, United Kingdom",
  "234 Donegall Place, Belfast, Northern Ireland, United Kingdom",
  "123 Grey Street, Newcastle, England, United Kingdom",
  "456 Northumberland Street, Newcastle, England, United Kingdom",
  "100 King Street, Nottingham, England, United Kingdom",
  "234 Queen Street, Nottingham, England, United Kingdom",
  "123 Above Bar Street, Southampton, England, United Kingdom",
  "456 High Street, Southampton, England, United Kingdom",
  "100 Gallowtree Gate, Leicester, England, United Kingdom",
  "234 High Street, Leicester, England, United Kingdom",
  "123 Bridge Street, Cambridge, England, United Kingdom",
  "456 King's Parade, Cambridge, England, United Kingdom",
  "100 High Street, Oxford, England, United Kingdom",
  "234 Cornmarket Street, Oxford, England, United Kingdom",
  "123 Western Road, Brighton, England, United Kingdom",
  "456 North Street, Brighton, England, United Kingdom",
  "100 Union Street, Aberdeen, Scotland, United Kingdom",
  "234 George Street, Aberdeen, Scotland, United Kingdom",
  "123 High Street, Dundee, Scotland, United Kingdom",
  "456 Nethergate, Dundee, Scotland, United Kingdom",
  "123 O'Connell Street, Dublin, Ireland",
  "456 Grafton Street, Dublin, Ireland",
  "789 Henry Street, Dublin, Ireland",
  "100 Dame Street, Dublin, Ireland",
  "234 Baggot Street, Dublin, Ireland",
  "123 Patrick Street, Cork, Ireland",
  "456 Oliver Plunkett Street, Cork, Ireland",
  "789 Grand Parade, Cork, Ireland",
  "100 Shop Street, Galway, Ireland",
  "234 Quay Street, Galway, Ireland",
  "456 Eyre Square, Galway, Ireland",
  "123 O'Connell Street, Limerick, Ireland",
  "456 William Street, Limerick, Ireland",
  "100 The Quay, Waterford, Ireland",
  "234 Barronstrand Street, Waterford, Ireland",
  "123 West Street, Drogheda, Ireland",
  "456 Laurence Street, Drogheda, Ireland",
  "100 Clanbrassil Street, Dundalk, Ireland",
  "234 Park Street, Dundalk, Ireland",
  "123 Main Street, Bray, Ireland",
  "456 Quinsborough Road, Bray, Ireland",
  "100 Kennedy Road, Navan, Ireland",
  "234 Trimgate Street, Navan, Ireland",
  "123 High Street, Kilkenny, Ireland",
  "456 Parliament Street, Kilkenny, Ireland",
];
